CREATE DATABASE DBDESIGN_PHONEBOOK
USE DBDESIGN_PHONEBOOK

CREATE TABLE PhoneBookV1
(
NickName nvarchar(30),
Phone varchar(50)
)

INSERT INTO PhoneBookV1 VALUES(N'Hoang NT','090x');

--AN CÓ HAI SỐ PHONE LÀM SAO
INSERT INTO PhoneBookV1 VALUES(N'An Nguyen','090x,091x');
INSERT INTO PhoneBookV1 VALUES(N'Binh Le','090x;091x;092x');
INSERT INTO PhoneBookV1 VALUES(N'Cuong Vo','090x-091x-092x');


SELECT * FROM PhoneBookV1

--PHÂN TÍCH:
/*
 ƯU ĐIỂM:
SELECT PHONE LÀ RA ĐƯỢC TẤT CẢ CÁC SỐ DI ĐỘNG

CHO TUI BIẾT SỐ ĐỂ BÀN, Ở NHÀ CỦA ANH BÌNH LÊ? TOANG !!!
QUY ƯỚC SỐ ĐẦU TIÊN LÀ SỐ ĐT BÀN, SỐ 2 LÀ DI ĐỘNG, SỐ 3 LÀ WORK

KHỐN NẠN VÌ QUY ƯỚC NGẦM,SỐ NÀO LÀ SỐ LOẠI NÀO, KHÓ NHỚ CHO NGƯỜI NHẬP LIỆU
TIÊU CHÍ NÀO ĐỂ CẲT CHUỖI

MỘT CELL MÀ CHỨA NHIỀU VALUES CÙNG KIỂU, ĐƯỢC GỌI LÀ CỘT ĐA TRỊ
MULTIVALUED COLUMN -> TIỀM ẨN NHIỀU KHÓ KHĂN CHO VIỆC XỬ LÍ DATA

NẾU 1 TALBLE CÓ 1 ĐA TRỊ NGƯỜI TA NÓI RẰNG NÓ KHÔNG ĐẠT CHUẨN 1 LEVEL THIẾT KẾ
1ST NORMALIZATION

CHUẨN 1, CHẤT LƯỢNG THIẾT KẾ TÍNH TỪ 1, 2, 3

THIẾT KẾ KÉM THÌ PHẢI NÂNG CẤP, KHÔNG CHƠI ĐA TRỊ
KHÔNG CHƠI GOM VALUE TRONG 1 CELL
2 CHIỀU FIX
CHIỀU NGANG(THÊM CỘT),CHIỀU DỌC(THÊM DÒNG)*****

*/

