USE Northwind

--------------------------------------------------------------------------------
--LÝ THUYẾT
--DB ENGINE HỖ TRỢ 1 LOẠT NHÓM HÀM DÙNG THAO TÁC TRÊN NHÓM DÒNG/CỘT, GOM DATA TÍNH TOÁN
--TRÊN ĐÁM DATA GOM NÀY  --NHÓM HÀM GOM NHÓM == AGGREGATE FUNCTIONS, AGGREGATION
--COUNT() SUM() MIN() MAX()

--****CÚ PHÁP CHUẨN:
--SELECT CỘT..., HÀM GOM NHÓM (),... FROM <TABLE>

--*CÚ PHÁP MỞ RỘNG:
--SELECT CỘT..., HÀM GOM NHÓM (),... FROM <TABLE>...WHERE.... GROUP BY (GOM THEO CỤM CỘT NÀO) HAVING....

--*HÀM COUNT() ĐẾM SỐ LẦN XUẤT HIỆN CỦA 1 CÁI GÌ ĐOÁ !
--		COUNT(*) ĐẾM SỐ DÒNG TRONG 1 CỘT
--		COUNT(CỘT NÀO ĐÓ)

---------------------------------------------------------------------------------

--1.IN RA DANH SÁCH CÁC NHÂN VIÊN
SELECT * FROM Employees

--2. ĐẾM XEM CÓ BAO NHIÊU NHÂN VIÊN
SELECT COUNT(*) FROM Employees

--3.CÓ BAO NHIÊU NV Ở LONDON
SELECT COUNT(*) FROM Employees WHERE CITY ='LONDON'

--4.CÓ BAO NHIÊU LƯỢT THÀNH PHỐ XUẤT HIỆN
SELECT COUNT(City) FROM Employees

--5.ĐẾM XEM CÓ BAO NHIÊU REGION
SELECT COUNT(Region) FROM Employees
--PPHATS HIỆN HÀM COUNT(CỘT), NẾU CELL CỦA CỘT NULL: KHÔNG ĐẾM

--6. ĐẾM BAO NHIÊU KHU VỰC NULL
SELECT COUNT(*) FROM Employees WHERE REGION IS NULL 

--7. CÓ BAO NHIÊU THÀNH PHỐ 
SELECT DISTINCT CITY FROM Employees
--TUI COI KẾT QUẢ TRÊN LÀ 1 TABLE
--SUB QUERY MỚI, COI 1 CÂU SELECT LÀ 1 TABLE

SELECT * FROM(
SELECT DISTINCT CITY FROM Employees) AS CITIES

SELECT COUNT(*) FROM (SELECT DISTINCT CITY FROM Employees) AS CITIES
SELECT COUNT(DISTINCT CITY) FROM Employees

--8.ĐẾM XEM MỖI THÀNH PHỐ CÓ BAO NHIÊU NHÂN VIÊN
--KHI CÂU HỎI CÓ TÍNH TOÁN GOM DATA(HÀM AGGREGATE) MÀ LẠI CHỨA TỪ MỖI
--GẶP TỪ MỖI CHÍNH LÀ CHIA ĐỂ ĐẾM

SELECT COUNT(CITY) FROM Employees GROUP BY CITY
SELECT CITY, COUNT(CITY) AS [NO EMPLOYESS] FROM Employees GROUP BY CITY

SELECT EmployeeID,City, COUNT(CITY) AS [NO EMPLOYESS] FROM Employees GROUP BY CITY, EmployeeID

--CHỐT HẠ:
--KHI XÀI HÀM GOM NHÓM, BẠN CÓ QUYỀN LIỆT KÊ TÊN CỘT LẺ Ở SELECT NHƯNG CỘT LẺ ĐÓ BẮT BUỘC PHẢI XUẤT HIỆN TRONG MỆNH ĐỀ GROUP BY
--ĐỂ ĐẢM BẢO LOGIC: CỘT HIỂN THỊ | SỐ LƯỢNG ĐI KÈM ĐỂ GOM THEO CỘT HIỂN THỊ MỚI LOGIC
-- CỨ THEO CỘT CITY MÀ GOM, CỘT CITY NẰM Ở SELECT HỢP LÍ
--MUỐN HIỂN THỊ SỐ LƯỢNG CỦA AI ĐÓ, GÌ ĐÓ THÌ GOM NHÓM THEO CÁI GÌ ĐÓ

--NẾU BẠN GOM THEO KEY/PK, VÔ NGHĨA HEN, VÌ KEY KHÔNG TRÙNG, MỖI THẰNG MỘT NHÓM
-- CÓ CỘT ĐỂ GOM NHÓM, CỘT ĐÓ SẼ DÙNG ĐỂ HIỂN THỊ KẾT QUẢ 

--9. HÃY CHO TUI BIẾT TP NÀO CÓ TỪ 2 NV TRỞ LÊN
SELECT CITY, COUNT(CITY) AS [NO EMOPLOYESS] FROM Employees GROUP BY CITY HAVING COUNT(*) >=2

--10. ĐẾM SỐ NHÂN VIÊN CỦA 2 THÀNH PHỐ SEATLE VÀ LONDON
SELECT CITY, COUNT(CITY) AS [NO EMPLOYESS] FROM Employees WHERE CITY IN ('LONDON', 'Seattle') GROUP BY City

--11. TRONG 2 THÀNH PHỐ LONDON VÀ SEATTLE THÀNH PHỐ NÀO CÓ NHIỀU HƠN 3 NHÂN VIÊN
SELECT CITY, COUNT(CITY) AS [NO EMPLOYESS] FROM Employees WHERE CITY IN ('LONDON', 'Seattle') GROUP BY City HAVING COUNT(*) >= 3

--12. ĐẾN XEM CÓ BAO NHIÊU ĐƠN HÀNG ĐÃ BÁN RA
SELECT * FROM Orders
SELECT COUNT(*) AS[NO ORDER] ORDER

--12.1 NƯỚC MỸ CÓ BAO NHIÊU ĐƠN HÀNG
--ĐI TÌM MỸ MÀ ĐẾM, LỌC MỸ RỒI TÍNH TIẾP, WHERE MỸ
--KHÔNG PHẢI LÀ CÂU GOM CHIA NHÓM, HONG CÓ MỖI QUỐC GIA BAO NHIÊU ĐƠN
--MỖI QUỐC GIA CÓ BAO NHIÊU ĐƠN, COUNT THEO QUỐC GIA,GROUP BY THEO QUỐC GIA
SELECT ShipCountry, COUNT(*) AS [USA 'S NO ORDER]  FROM Orders WHERE ShipCountry ='USA' GROUP BY ShipCountry

--12.2 MỸ PHÁP ANH CHIẾM TỔNG CỘNG BAO NHIÊU ĐƠN HÀNG
SELECT  COUNT(*) AS [NO ORDER] FROM Orders WHERE ShipCountry IN ('USA','UK','FRANCE') 
SELECT * FROM Orders

--12.3 MỸ PHÁP ANH MỖI QUỐC GIA BAO NHIÊU ĐƠN HÀNG
SELECT ShipCountry,COUNT(ShipCountry) AS [NO ORDER] FROM Orders WHERE ShipCountry IN ('USA','UK','FRANCE') GROUP BY ShipCountry

--12.4 TRONG 3 QUỐC GIA A P M QUỐC GIA NÀO CÓ TỪ 100 ĐƠN HÀNG TRỞ LÊN
SELECT ShipCountry,COUNT(ShipCountry) AS [NO ORDER] FROM Orders WHERE ShipCountry IN ('USA','UK','FRANCE') GROUP BY ShipCountry HAVING COUNT(*) > 100


--13. ĐẾM XEM CÓ BAO NHIÊU MẶT HÀNG CÓ TRONG KHO
SELECT COUNT(*) AS [NO CATEGORIES NAME] FROM Categories

--14. ĐẾM XEM CÓ BAO NHIÊU LƯỢT QUỐC GIA ĐÃ MUA HÀNG
SELECT * FROM Orders
SELECT  COUNT(*) AS [NO REGION BUY] FROM Orders 

--15. ĐẾM XEM CÓ BAO NHIÊU QUỐC GIA ĐÃ MUA HÀNG MỖI QUỐC GIA MỘT LẦN
SELECT COUNT (DISTINCT ShipCountry) AS[REGION HAS BEEN BUY] FROM Orders
--16. ĐẾM SỐ LƯỢNG ĐƠN HÀNG CỦA MỖI QUỐC GIA
SELECT ShipCountry,COUNT(ShipCountry) [NO REGION BUY] FROM Orders GROUP BY ShipCountry

--17.QUỐC GIA NÀO CÓ TỪ 10 ĐƠN HÀNG TRỞ LÊN
SELECT ShipCountry,COUNT(ShipCountry) [NO REGION BUY] FROM Orders GROUP BY ShipCountry HAVING COUNT(*) >10

--18.ĐẾM XEM MỖI CHỦNG LOẠI HÀNG CÓ BAO NHIÊU MẶT HÀNG

--19. TRONG 3 QUỐC GIA A P M, QUỐC GIA NÀO CÓ NHIỀU ĐƠN HÀNG NHẤT

--20. 